In [1]:

import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [14]:

arr1,arr2 = (list(map(int,input().split())) for i in range(2))
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print("Concatenated array is:",np.concatenate((arr1,arr2)))
print("sorted array is :",np.sort(np.concatenate((arr1,arr2))))

1 2 5 6 7
8 4 3 2 1
Concatenated array is: [1 2 5 6 7 8 4 3 2 1]
sorted array is : [1 1 2 2 3 4 5 6 7 8]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [6]:

arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print("dimensions :",arr.shape,"\n size",arr.size)

dimensions : (3, 3) 
 size 9


In [15]:
a = np.array([2, 4])
print("1D array shape is: ",a.shape)
b = np.expand_dims(a, axis=0)
print("After converting a 1D array into a 2D array the shape is :",b.shape)

1D array shape is:  (2,)
After converting a 1D array into a 2D array the shape is : (1, 2)


In [13]:
import numpy as np

array_2d_square = np.square([1,2,3])

print("Squared Array:\n",array_2d_square)

array_2d_square1 = np.square([4,5,6])

print("Squared Array1:\n",array_2d_square1)

print('Horizontal Append:', np.hstack((array_2d_square, array_2d_square1)))

print('Vertical Append:', np.vstack((array_2d_square, array_2d_square1)))

Squared Array:
 [1 4 9]
Squared Array1:
 [16 25 36]
Horizontal Append: [ 1  4  9 16 25 36]
Vertical Append: [[ 1  4  9]
 [16 25 36]]


In [12]:
list1 = [4,6,7,2,8,9]
list1 = list(set(list1))
print(list1)
print(len(list1))

[2, 4, 6, 7, 8, 9]
6
